Gcp deploy
Nelwell/lmn pull request #57
Opened 2021-04-28 21:13 UTC by Nelwell

2021-04-30 18:13 UTC, apratt101300 requested changes
This will be adding/modifying 152 files. Do you think we could leave this as a PR instead of merging?

2021-05-01 11:06 UTC, Nelwell commented on lmnop_project/settings.py
> +# SECRET_KEY = 'o+do-*x%zn!43h+unn!46(xp$e6&)=y63v#lj3ywjuy8cihz9f'
I don't think we do.  It's randomly a randomly generated key instead of hard-coded and set.

2021-05-01 11:09 UTC, Nelwell commented on lmnop_project/settings.py
> +# SECRET_KEY = 'o+do-*x%zn!43h+unn!46(xp$e6&)=y63v#lj3ywjuy8cihz9f'
oh my bad i misread your comment. Yes I should have deleted that commented-out key.  I forgot to remove it after testing the randomly-generated one.

2021-05-01 11:13 UTC, Nelwell commented on lmnop_project/settings.py
> +# STATIC_URL = '/static/'
Great catch.  Somehow I skipped over that slide in the ppt.

2021-05-01 11:26 UTC, Nelwell commented
> 
> 
> This will be adding/modifying 152 files. Do you think we could leave this as a PR instead of merging?

I have nothing against leaving it in its own branch if you're afraid it might break something? I don't know why it would since everything works on my end over here but it might be an unnecessary risk. So we can leave it if you want.

2021-05-10 20:07 UTC, andrea-pratt commented
Everything's working now. Looks good!

2021-05-10 20:07 UTC, merged